### ISSUE TITLE
Try System Font Stack

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-io#27]
From create-react-app:

```css
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", 
    "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", 
    sans-serif;
}
    
code {
  font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
    monospace;     
} 
]
```
